import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";

const OnlineExamPage = (props) => {
  useEffect(() => {
    document.title = `Online Exam - QSC Automation`;
  }, []);

  const [attributes] = useState([
    {
      type: "select",
      apiType: "API",
      selectApi: "exam-type/select",
      placeholder: "Exam",
      name: "exam",
      validation: "",
      default: "",
      tag: true,
      label: "Exam",
      showItem: "examType",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: true,
    },
    {
      type: "text",
      placeholder: "Exam Title",
      name: "title",
      validation: "",
      default: "",
      tag: true,
      label: "Title",
      showItem: "",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "CSV",
      selectApi: "Trial,Main",
      placeholder: "Exam Type",
      name: "examType",
      validation: "",
      default: "Trial",
      tag: true,
      label: "Exam Type",
      showItem: "examType",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: true,
    },
    {
      type: "textarea",
      placeholder: "Description",
      name: "description",
      validation: "",
      default: "",
      tag: false,
      label: "Description",
      showItem: "",
      required: false,
      view: false,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Total Questions",
      name: "totalQuestions",
      validation: "",
      default: "10",
      tag: true,
      label: "Questions",
      showItem: "",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Duration (minutes)",
      name: "duration",
      validation: "",
      default: "60",
      tag: true,
      label: "Duration (min)",
      showItem: "",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Marks per Question",
      name: "marksPerQuestion",
      validation: "",
      default: "1",
      tag: false,
      label: "Marks/Q",
      showItem: "",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Negative Marking",
      name: "negativeMarking",
      validation: "",
      default: "0",
      tag: false,
      label: "Neg. Marks",
      showItem: "",
      required: false,
      view: false,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Passing Percentage",
      name: "passingPercentage",
      validation: "",
      default: "40",
      tag: true,
      label: "Pass %",
      showItem: "",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "datetime",
      placeholder: "Exam Start Date",
      name: "examDate",
      validation: "",
      default: "",
      tag: false,
      label: "Exam Start",
      showItem: "",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "datetime",
      placeholder: "Exam End Date",
      name: "examEndDate",
      validation: "",
      default: "",
      tag: false,
      label: "Exam End",
      showItem: "",
      required: false,
      view: false,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "CSV",
      selectApi: "detailed,score_only,pass_fail",
      placeholder: "Result Visibility",
      name: "resultVisibility",
      validation: "",
      default: "score_only",
      tag: false,
      label: "Result Visibility",
      showItem: "resultVisibility",
      required: false,
      view: true,
      add: true,
      update: true,
      filter: true,
    },
    {
      type: "number",
      placeholder: "Practice Questions Count",
      name: "practiceQuestionCount",
      validation: "",
      default: "10",
      tag: false,
      label: "Practice Q Count",
      showItem: "",
      required: false,
      view: false,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "CSV",
      selectApi: "true,false",
      placeholder: "Shuffle Questions",
      name: "shuffleQuestions",
      validation: "",
      default: "true",
      tag: false,
      label: "Shuffle",
      showItem: "shuffleQuestions",
      required: false,
      view: false,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "CSV",
      selectApi: "true,false",
      placeholder: "Publish Result",
      name: "publishResult",
      validation: "",
      default: "false",
      tag: true,
      label: "Published",
      showItem: "publishResult",
      required: false,
      view: true,
      add: false,
      update: true,
      filter: true,
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        api={`online-exam`}
        itemTitle={{
          name: "title",
          type: "text",
          collection: "",
        }}
        shortName={`Online Exam`}
        formMode={`double`}
        surfaceTheme={"district"}
        {...props}
        attributes={attributes}
      />
    </Container>
  );
};

export default Layout(OnlineExamPage);
