import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const ExamCenterRegistration = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = "Outside Exam Attendance List - QSC Automation";
  }, []);

  const [attributes] = useState([
    {
      type: "title",
      title: "Basic Information",
      add: false,
      export: false,
    },
    {
      type: "text",
      placeholder: "Name Of Applicant",
      name: "nameOfApplicant",
      validation: "",
      default: "",
      label: "Name Of Applicant",
      tag: true,
      required: true,
      view: true,
      add: false,
      update: false,
      customClass: "full",
    },
    {
      type: "select",
      placeholder: "Gender",
      name: "gender",
      validation: "",
      default: "",
      tag: false,
      label: "Gender",
      showItem: "Gender",
      required: true,
      view: true,
      filter: false,
      add: false,
      update: false,
      apiType: "CSV",
      selectApi: "Male,Female",
    },
    {
      type: "number",
      placeholder: "Mobile Number",
      name: "mobileNumber",
      validation: "",
      default: "",
      label: "Mobile Number",
      tag: true,
      required: true,
      view: true,
      add: false,
      update: false,
    },
    {
      type: "number",
      placeholder: "Whatsapp Number",
      name: "whatsappNumber",
      validation: "",
      default: "",
      label: "Whatsapp Number",
      tag: false,
      required: true,
      add: false,
      view: true,
      update: false,
    },
    {
      type: "textarea",
      placeholder: "Address",
      name: "address",
      validation: "",
      default: "",
      label: "Address",
      tag: false,
      required: true,
      add: false,
      view: true,
      update: false,
    },
    {
      type: "number",
      placeholder: "Age",
      name: "age",
      validation: "",
      default: "",
      label: "Age",
      tag: false,
      required: true,
      add: false,
      view: true,
    },
    {
      type: "title",
      title: "Qualification Details",
      add: false,
      export: false,
    },
    {
      type: "textarea",
      placeholder: "Educational Qualification",
      name: "educationalQualification",
      validation: "",
      default: "",
      label: "Educational Qualification",
      tag: true,
      required: true,
      add: false,
      view: true,
      update: false,
    },
    {
      type: "title",
      title: "Exam Details",
      add: false,
      export: false,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "exam-type/select",
      placeholder: "Name of Exam Appearing Now",
      updateOn: "",
      name: "nameOfExamAppearingNow",
      validation: "",
      showItem: "examType",
      search: false,
      default: "",
      tag: true,
      label: "Name of Exam Appearing Now",
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
      export: false,
      customClass: "full",
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "district/select",
      placeholder: "District",
      name: "district",
      validation: "",
      showItem: "district",
      default: "",
      tag: false,
      label: "District",
      search: false,
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
      customClass: "full",
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "area/get-area-by-district",
      placeholder: "Area",
      updateOn: "district",
      name: "area",
      search: false,
      validation: "",
      showItem: "area",
      default: "",
      tag: false,
      label: "Area",
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
    },
    {
      type: "select",
      placeholder: "Mode of Study",
      name: "status",
      validation: "",
      default: "",
      customClass: "full",
      tag: true,
      label: "Mode of Study",
      showItem: "",
      required: true,
      view: true,
      filter: false,
      add: false,
      update: false,
      apiType: "CSV",
      selectApi: "Private,Regular",
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "center-registration/area",
      placeholder: "Study Center",
      customClass: "full",
      updateOn: "area",
      name: "centerRegistration",
      validation: "",
      showItem: "nameOfCenter",
      default: "",
      tag: false,
      label: "Study Center",
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
      search: false,
      export: true,
    },
    {
      type: "text",
      placeholder: "Affiliation  Number",
      updateOn: "",
      name: "affiliation",
      collection: "affiliation",
      validation: "",
      showItem: "",
      default: "",
      tag: true,
      label: "Affiliation  Number",
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
      search: false,
    },
    {
      type: "select",
      placeholder: "പരീക്ഷ എഴുതാനുള്ള കേന്ദ്രം നിങ്ങളുടെ ജില്ലയിൽ തന്നെയാണോ വേണ്ടത്?",
      name: "outsideCenter",
      validation: "",
      default: "No",
      tag: false,
      label: "പരീക്ഷ എഴുതാനുള്ള കേന്ദ്രം നിങ്ങളുടെ ജില്ലയിൽ തന്നെയാണോ വേണ്ടത്?",
      showItem: "",
      required: true,
      view: true,
      filter: false,
      add: false,
      update: false,
      apiType: "CSV",
      selectApi: "Yes,No",
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "district/select",
      placeholder: "Exam District",
      name: "examDistrict",
      validation: "",
      showItem: "district",
      default: "",
      tag: true,
      label: "Exam എഴുതാൻ ഉദ്ദേശിക്കുന്ന ജില്ല തെരഞ്ഞെടുക്കുക",
      search: false,
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "exam-registration/district-center",
      placeholder: "Outside Exam Center",
      updateOn: "examDistrict",
      name: "outsideExamCenter",
      showItem: "centerName",
      validation: "",
      default: "",
      tag: true,
      label: "Outside Exam Center",
      required: true,
      view: true,
      add: false,
      update: false,
      filter: false,
      search: false,
    },
    {
      type: "title",
      title: "Payment Information",
      add: false,
      export: false,
    },
    {
      type: "number",
      placeholder: "Gpay Number",
      name: "feeDetails",
      validation: "",
      default: "",
      info: "Regular വിഭാഗത്തിന് 100 രൂപയും Private വിഭാഗത്തിന് 150 രൂപയുമാണ് രജിസ്ട്രേഷൻ ഫീസ്. തുക 7994162608 നമ്പറിൽ ഗൂഗിൾ പേ ചെയ്യുക. ഏത് നമ്പറിൽ നിന്നാണോ ഗൂഗിൾ പേ ചെയ്തത്, ആ നമ്പർ ഇവിടെ നൽകുക.",
      label: "Gpay Number",
      required: true,
      add: false,
      view: true,
      export: true,
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        api={"exam-registration/outside-center-list"}
        itemTitle={{
          name: "nameOfApplicant",
          type: "text",
          collection: "",
        }}
        shortName={"Outside Exam Attendance List"}
        formMode={"single"}
        displayColumn="double"
        defaultFilter={{ outsideCenter: "No" }}
        surfaceTheme={"district"}
        {...props}
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};

export default Layout(ExamCenterRegistration);
